# Generated by Django 5.1 on 2024-10-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_type',
            field=models.CharField(choices=[('client', 'Client')], max_length=10),
        ),
    ]
