# Generated by Django 5.1 on 2024-10-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_types',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('cashier', 'Cashier'), ('info', 'Information')], max_length=10),
        ),
    ]
